### ISSUE TITLE
Citation file

### ISSUE THREAD

**Issue by matgrand** [phillipd94/pyclothoids#13]
Hi, I wanted to cite this repo because I heavily used it in an academic project. Great job btw. Can you add a citation file (.cff) so that I can do that easily with bibitex?  I think it should be something like this: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

**Comment by johschmitz** [comment]
I am not the main author of this Python wrapper  (only have a small contribution) and don't want to recommend not to give credit where its due but having worked in academia myself, I honestly believe you should probably cite the original C++ project instead, which contains the core of the business logic and does all the heavy lifting. The author (Prof. Bertolazzi) also published some papers on the topic which are most probably better suited for a scientific citation.
See
https://github.com/ebertolazzi/Clothoids
https://ebertolazzi.github.io/Clothoids/

**Comment by johschmitz** [comment]
Regarding citing the wrapper repo as well: Try to use an @misc entry in your .bib file.
https://tex.stackexchange.com/questions/35977/how-to-add-a-url-to-a-latex-bibtex-file

**Comment by matgrand** [comment]
Thank you very much
