### ISSUE TITLE
 clothoid-circular-clothoid figures with constraints

### ISSUE THREAD

**Issue by Na3aga** [phillipd94/pyclothoids#14]
How to calculate clothoid-circular-clothoid figures with constraints on the circle radius size? 
Is it possible to rotate with this library using the clothoid-circular-clothoid figures and not only clothoids?

**Comment by phillipd94** [comment]
The Clothoid object from this library can accurately represent circles as well, but constrained optimization of piecewise clothoid/circle trajectories is well beyond the scope of this library.  Our goal is to give a pythonic and simple representation of these curves that other optimization code can build upon if needed.  This library would be a good candidate for representing the geometric curves themselves, but for any specific optimization involving multiple curves you can use any of the available python optimization libraries and use pyclothoids to build the cost functions or constraints to pass in to them.  While the requested functionality would certainly be valuable, the scope would demand a separate library beyond the scope of pyclothoids to implement the required optimizations efficiently.

**Comment by johschmitz** [comment]
I think one needs to implement this on the C++ level. Consider opening an issue in the other repository. Also a good workaround I think is to instead use the triple clothoid solver which is already available.
