### ISSUE TITLE
This is great! 

### ISSUE THREAD

**Issue by inatale93** [phillipd94/pyclothoids#3]
We have been looking for something similar for a long time! This is so awesome, thank you a lot! 
We will probably use your work in our tool https://github.com/pyoscx/scenariogeneration 
Please let us know how you want to be cited :) 

//Irene

**Comment by phillipd94** [comment]
Thanks, it's always satisfying to see my work put to good use!

If this ends up being useful to your project, I would sure appreciate if you'd give me a shout in the "related works" section of your readme, or whatever other attribution method seems most appropriate.

**Comment by inatale93** [comment]
Now the integration is done, together with reference in the README. You can close this issue if you want :)
