### ISSUE TITLE
Binary package(s) 

### ISSUE THREAD

**Issue by johschmitz** [phillipd94/pyclothoids#5]
I would like to ask if you could release binary packages so that the user doesn't have the trouble of compiling it during pip install? I believe some other packages like numpy are doing this:
https://numpy.org/doc/stable/dev/releasing.html

Usecase: this packages is used in https://github.com/pyoscx/scenariogeneration which is then used by https://github.com/johschmitz/blender-driving-scenario-creator
Installing the Blender add-on becomes very complicated due to the compilation step. There is also the problematic case with slightly older Linux distributions which don't bring the Python 3.9 headers and then it gets even harder.

**Comment by johschmitz** [comment]
I guess this might be helpful:
https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

**Comment by phillipd94** [comment]
Per my understanding, pip will always check to see if a wheel is on pypi for the target system, and only compiles the code during install if a wheel isn't available.  Right now I only have binaries for 64 bit windows on pypi, but I've done a bit of investigating and I should be able to build and release a binary compatible with manylinux on a reasonable timeframe.  Would that be sufficient for the needs of your project?  The package would still need to compile at install if there was a target system that wasn't included in manylinux or windows 64 bit.

**Comment by johschmitz** [comment]
Cool, I did not implement that exact same thing myself so far but I guess this should work. In fact numpy seems to also be using manylinux. I'll definitely report back about the results as soon as you release something. Furthermore, I suggest that you implement it using GitHub Actions. Then you just tag a new version whenever you are happy with it and it will be released automatically. No need for so much manual work on your local computer anymore 😊 I am only releasing to the Github release page this way but it should probably also work fine for PyPI as described in the links above.
See:
https://github.com/johschmitz/blender-driving-scenario-creator/blob/master/.github/workflows/release.yaml
In there I am using
https://github.com/anton-yurchenko/git-release
And I love that it also takes care of publishing my changelog alongside the assets to the release page. I hope that you can combine it with manylinux. 

Btw I am also considering to directly use your lib now inside my tool to interactively calculate some road geometries. Let's see how that turns out. Also I was wondering if it would eventually make sense for your code to become a part of numpy or if it is too special or incompatible with the philosophy or something. In any case, whatever path you choose, keep up the great work!

**Comment by johschmitz** [comment]
@phillipd94 Let me know if I can support you with this issue. Would also love to have a video call and give you a little demo of how I am using your library if that is interesting for you.
